name: Django CI

on:
  push:
    branches: [ "dev" ]
  pull_request_target: # To be able to access the secrets
    branches: [ "dev" ]
    types: [opened] # run workflow only for opened pull requests
    paths: #run workflow only when.py files are modified
    - "**.py"

jobs:
  build: # job id

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
